root: true
env:
  node: true
  es6: true

extends:
  - 'plugin:vue/vue3-essential'
  - 'standard-with-typescript'
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'plugin:prettier/recommended'

ignorePatterns:
  - '**/dist/**'
  - '**/node_modules/**'
  - '!.vuepress/**'
  - '**/.vuepress/.cache/**'
  - '**/.vuepress/.temp/**'

parserOptions:
  parser: '@typescript-eslint/parser'
  project:
    - './tsconfig.json'
  ecmaVersion: 'latest'
  sourceType: 'module'

plugins:
  - 'vue'

rules:
  '@typescript-eslint/naming-convention':
    - warn
    - selector: default
      format:
        - camelCase
      leadingUnderscore: allowSingleOrDouble
      trailingUnderscore: allow

    - selector:
        - variable
      format:
        - camelCase
        - PascalCase
        - UPPER_CASE
      leadingUnderscore: allowSingleOrDouble
      trailingUnderscore: allowSingleOrDouble

    - selector:
        - parameter
      format:
        - camelCase
        - PascalCase
      leadingUnderscore: allow
      trailingUnderscore: allow

    - selector:
        - property
      format: null
      custom:
        regex: (^/.*/$|^@|^[a-z]+(?:-[a-z]+)*?$)
        match: true
      # allow locales path like `/zh/`, alias starting with `@` and css property like `line-width`
      filter: (^/.*/$|^@|^[a-z]+(?:-[a-z]+)*?$)
      leadingUnderscore: allow
      trailingUnderscore: allow

    - selector:
        - property
      format:
        - camelCase
        - PascalCase
        - UPPER_CASE
      leadingUnderscore: allow
      trailingUnderscore: allow

    - selector: typeLike
      format:
        - PascalCase
